# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9fff0f976b6d1ae8f9cb5b703e965bd817c189b5a708da558fa38c87c7e1064ac9f9cc94e8b5a4cd83c20bd73db8b27a91ba2cca113a0fabec9082aa3330c6ad

test:
  secret_key_base: 58b6506be1b884e244993690c13c1516468b427cd10e4b70b0a6f900b0b494c2bb7a775daa547ba4c8630b1e5b7501d7a9c6ff05deed824e6865fd974a018deb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
